# ==========================================
# Application
# ==========================================
spring.application.name=ReelCosmos

server.port=${PORT:8080}


# ==========================================
# PostgreSQL
# ==========================================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# ==========================================
# Redis
# ==========================================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}


# ==========================================
# JWT
# ==========================================
jwt.secret=ReelCosmosSuperSecretKeyForJwtAuthentication2026ProductionSecurityKey123456789

jwt.access-token-expiration=900000

jwt.refresh-token-expiration=604800000


# ==========================================
# TMDB
# ==========================================
tmdb.base-url=https://api.themoviedb.org/3

tmdb.api-key=19994ecfb154690fcf5f2dff14ccd6aa

tmdb.image-base-url=https://image.tmdb.org/t/p


# ==========================================
# Swagger
# ==========================================
springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.path=/swagger-ui.html


# ==========================================
# Logging
# ==========================================
logging.level.org.springframework.security=INFO

logging.level.org.hibernate.SQL=INFO